#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 03, 2021 10:50:14 AM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global battery_6V
    battery_6V = tk.IntVar()
    global internal
    internal = tk.IntVar()
    global battery_target_current
    battery_target_current = tk.StringVar()
    battery_target_current.set('battery_target_current')
    global battery_actual_current
    battery_actual_current = tk.StringVar()
    battery_actual_current.set('')
    global battery_target_voltage
    battery_target_voltage = tk.StringVar()
    battery_target_voltage.set('battery_target_voltage')
    global battery_actual_voltage
    battery_actual_voltage = tk.StringVar()
    battery_actual_voltage.set('')
    global on_selected
    on_selected = tk.IntVar()
    global stat_1
    stat_1 = tk.StringVar()
    stat_1.set('')
    global stat_2
    stat_2 = tk.StringVar()
    stat_2.set('')
    global power_on_not
    power_on_not = tk.StringVar()
    global plus_load
    plus_load = tk.StringVar()
    global oven_on
    oven_on = tk.IntVar()
    global cool
    cool = tk.IntVar()
    global oven_temperature
    oven_temperature = tk.StringVar()
    oven_temperature.set('')
    global comp_temperature
    comp_temperature = tk.StringVar()
    comp_temperature.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def battery_type_change():
    print('GUI_support.battery_type_change')
    sys.stdout.flush()

def cool_on():
    print('GUI_support.cool_on')
    sys.stdout.flush()

def current_change():
    print('GUI_support.current_change')
    sys.stdout.flush()

def internal_external_battery():
    print('GUI_support.internal_external_battery')
    sys.stdout.flush()

def oven_on():
    print('GUI_support.oven_on')
    sys.stdout.flush()

def power_on():
    print('GUI_support.power_on')
    sys.stdout.flush()

def voltage_change():
    print('GUI_support.voltage_change')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()




